version: 0.2

phases:
  install:
    commands:
      - echo "Installing NVM (Node Version Manager)..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - . /root/.nvm/nvm.sh
      - nvm install 18
      - nvm use 18
      - node -v
      - npm -v
      - echo "Installing source NPM dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # - npm test

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

  post_build:
    commands:
      - echo "Post-build steps..."
      - echo "Zipping the application including node_modules..."
      - zip -r SentimentAnalysis.zip . -x ".*" "*/*.log"
      - echo "Artifact zip created."

artifacts:
  files:
    - '**/*'
  discard-paths: no
