version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: - n latest
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # - npm test

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

  post_build:
    commands:
      - echo "Post-build steps..."
      - echo "Zipping the application including node_modules..."
      - zip -r SentimentAnalysis.zip . -x ".*" "*/*.log"
      - echo "Artifact zip created."

artifacts:
  files:
    - '**/*'
  discard-paths: no
