version: 0.2

phases:
  install:
    commands:
      - echo "Manually installing Node.js version 18..."
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
      - node -v
      - npm -v
      - echo "Installing source NPM dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      # - npm test

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

  post_build:
    commands:
      - echo "Post-build steps..."
      - echo "Zipping the application including node_modules..."
      - zip -r SentimentAnalysis.zip . -x ".*" "*/*.log"
      - echo "Artifact zip created."

artifacts:
  files:
    - '**/*'
  discard-paths: no
